console.log("Welcome to Rock, Paper, Scissors!");


//function to pick a random integer for computer choice

let randomInteger = Math.floor(Math.random()* 3);

//function to match rock, paper or scissors to a number generated by the above function.

function getComputerChoice(randomInteger){
    if (randomInteger == 0) {
        compChoice = "rock"

    } else if (randomInteger == 1) {
        compChoice = "paper"


    } else if (randomInteger==2) {
        compChoice = "scissors"

    }
    return compChoice 
}

//set a variable to simplify code later on
let computerChoice = getComputerChoice(randomInteger)

console.log (computerChoice)



//create popup to ask for user choice

let userInput = window.prompt("Rock, paper or scissors - What's your choice?")

//function to make userInput case insensitive and define the user input

function getHumanChoice(userInput) {
    userInput = userInput.toLowerCase();
    return userInput
}

// set a variable to simplify code later on
let humanChoice = getHumanChoice(userInput)

console.log (humanChoice)

//variables to store score
let humanScore = 0;
let computerScore =  0;



