console.log("Welcome to Rock, Paper, Scissors!");


//function to pick a random integer for computer choice

let randomInteger = Math.floor(Math.random()* 3);

//function to match rock, paper or scissors to a number generated by the above function.

function getComputerChoice(randomInteger){
    if (randomInteger == 0) {
        compChoice = "rock"

    } else if (randomInteger == 1) {
        compChoice = "paper"


    } else if (randomInteger==2) {
        compChoice = "scissors"

    }
    return compChoice 
}

//set a variable to simplify for later on
const computerChoice = getComputerChoice(randomInteger);


let userInput = window.prompt("Rock, paper or scissors - What's your choice?")

//function to make userInput case insensitive and define the user input

function getHumanChoice(userInput) {
    userInput = userInput.toLowerCase();
    return userInput
    
}

// set a variable to simplify code later on
const humanChoice = getHumanChoice(userInput)


//variables to store score
let humanScore = 0;
let computerScore =  0;

//function to compare computer and human answer and assign a winner

function playRound(humanChoice, computerChoice) {
    if (humanChoice == computerChoice) {
        return "tie"
    
    } else if (humanChoice == "rock" && computerChoice == "scissors") {
        return "human"

    
    } else if (humanChoice == "scissors" && computerChoice == "paper") {
        return "human"
    
    } else if (humanChoice == "paper" && computerChoice == "rock") {
        return "human"

    } else {
        return "computer"
    }
}

const gameRound = playRound(humanChoice, computerChoice);

//increment computerScore and humanScore by 1 

if (gameRound === "human"){
    humanScore ++;
}

else if (gameRound === "computer"){
    computerScore++;
}

//write out winning/losing declarations to console
function winningDeclaration (){
    if (gameRound === "human") {
        console.log("You win! " + userInput + " beats " + computerChoice)
    } else if (gameRound === "computer"){    
        console.log("You lose :( " + computerChoice + " beats " + userInput)
    } else if (gameRound === "tie") {
        console.log("It's a tie!")
    }
}


//function to control the flow of the game

function playGame () {
    console.log ("Your choice:" + humanChoice);
    console.log ("Computer's choice: " + computerChoice);
    winningDeclaration (gameRound)
    console.log("Your score: " + humanScore);
    console.log("Computer's score: " + computerScore);
}

console.log("Round 1");
playGame()

console.log("Round 2");
playGame()

console.log("Round 3");
playGame()

console.log("Round 4");
playGame()

console.log("Round 5");
playGame()

if (humanScore > computerScore) {
    console.log("You win!")
} else {
    console.log("Computer wins! Boo you!")
}
    